### ISSUE TITLE
Screenshot updaten

### ISSUE THREAD

**Issue by zonky2** [BugBuster1701/docs#10]
bei den PDFs: für Screenshot den Scrollbalken "nach rechts" ziehen, damit man auch den Pfad-Namen sieht...

![shot210](https://cloud.githubusercontent.com/assets/1045318/15643113/c21a19e2-264b-11e6-8478-c4e4e4dc6057.jpg)

**Comment by BugBuster1701** [comment]
Ja, das habe ich auch schon gesehen, Danke nochmal für den Hinweis.
GitBook ist da knallhart und wandelt das so um. Muss ich mal zweizeilig machen oder scrollen.

**Comment by BugBuster1701** [comment]
Korrigiert in Docs Version 1.6.1, Handbuch HTML und PDF neu generiert
