### ISSUE TITLE
C3 nach C4 Bundle Klasse registrieren

### ISSUE THREAD

**Issue by do-while** [BugBuster1701/docs#15]
Hallo Glen,

Du hast einen Fehler in Folie 13.3:
Richtig muss es heissen:
```PHP
"autoload":{
    "psr-4": {
        "Vendor\\DemoBundle\\": "src/"
    }
},
"extra":{
    "contao-manager-plugin": "Vendor\\DemoBundle\\ContaoManager\\Plugin"
}
```
Es muss DemoBundle und nicht VendorDemoBundle sein.

Anderenfalls installiert der Contao Manager und stellt sich dann selbst ein Bein, nur noch 500er Fehler. Die angebotenen Reparaturversuche treffen nicht zu. Abhilfe war die Kommandozeile mit composer update, das dann alles installierte wieder sauber ausbaut.

Hagen

**Comment by BugBuster1701** [comment]
Danke, gefixt, PDF ziehe ich gleich nach.
