### ISSUE TITLE
Demo CSS Dateien werden per default eingebunden

### ISSUE THREAD

**Issue by chriza** [BugBuster1701/docs#36]
Contao 5.3

Entgegen der Beschreibung im Handbuch für Contao 5 werden die Demo CSS-Dateien per default eigebunden.

Ist es möglich, dieses wieder rückgängig zu machen?

Beste Grüße

**Comment by BugBuster1701** [comment]
Wie kommst du darauf? Welche Datei soll das denn sein und wo wird die eingebunden?
Und um welche Erweiterung handelt es sich?

**Comment by chriza** [comment]
Hallo Herr Langner,

 

im HEADER-Bereich werden die CSS-Dateien eingebunden:

 



 

Beste Grüße

Christoph Zander

 

Von: Glen Langer ***@***.***> 
Gesendet: Mittwoch, 3. Juli 2024 22:04
An: BugBuster1701/docs ***@***.***>
Cc: chriza ***@***.***>; Author ***@***.***>
Betreff: Re: [BugBuster1701/docs] Demo CSS Dateien werden per default eingebunden (Issue #36)

 

Wie kommst du darauf? Welche Datei soll das denn sein und wo wird die eingebunden?

**Comment by BugBuster1701** [comment]
Das ist  normal, wo sonst. Aber welche? Von welcher Erweiterung?

**Comment by BugBuster1701** [comment]
ok, weiter hier https://github.com/BugBuster1701/contao-visitors-bundle/issues/173
