### ISSUE TITLE
Contao?

### ISSUE THREAD

**Issue by fiedsch** [BugBuster1701/docs#9]
In der readme.md steht "User guide for the Contao extension: GitHub Changelog Generator" (dito beim deutschen Titel). Contao ist doch hier gar nicht beteiligt -- oder habe ich etwas übersehen?

**Comment by BugBuster1701** [comment]
Hmm, ja, geht im Prinzip für alle Projekte auf GitHub. Werde ich mal anpassen.

**Comment by BugBuster1701** [comment]
Macht der Gewohnheit vor allem "Contao" zu schreiben :-)
